FROM python:3.12-slim

WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

COPY requirements/migrate.txt ./
RUN pip install --no-cache-dir -r migrate.txt

COPY ai_alembic.ini ./
COPY ai_alembic ./ai_alembic

ENTRYPOINT ["alembic", "-c", "ai_alembic.ini"]
CMD ["upgrade", "head"]
